### ISSUE TITLE
[FEAT] add country emoji

### ISSUE THREAD

**Issue by mosheavni** [ragnarok22/whereami.nvim#2]
take a look at my implementation:
https://github.com/mosheavni/dotfiles/blob/8681a0660a5567d898a0e43673921b8daccecf2e/.config/nvim/lua/user/keymaps.lua#L328-L341

https://github.com/mosheavni/dotfiles/blob/e400ad553fc7ef53f27ef6231f3e8df079b8ff20/.config/nvim/lua/user/utils.lua#L140-L152

maybe it's not perfect, but you can take whatever code you want :)

**Comment by ragnarok22** [comment]
Interesting code. I'll take a look. I'm learning Lua and this is my first plugin but I'm intend to add more features and improvments. Thanks!
